import pytse_client

from crawler.exceptions import TSECrawlException


def update_symbol(symbol):
    try:
        pass
        # TODO
    except:
        raise TSECrawlException('کرال اطلاعات با مشکل رو به رو شد!'
                                'از صحت وجود نماد اطمینان حاصل کنید سپس بعد از مدتی دوباره تلاش کنید.'
                                )
